train_data_dir: [
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.0-0.05169578, 1],
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.05169578-0.10339156, 1],
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.10339156-0.15508734, 1],
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.15508734-0.20678312, 1],
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.20678312-0.25847891,1],
  [/home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/train/0.25847891-1,1]
]
# item of train_data_dir: [path, weight]

valid_data_dir: [
  /home/chadrick/prj/kaggle/hubmap/data_prep/testoutput/split_trainval_from_coverage_split/210313_171723/valid

]


ckpt: null


gpu: 0
lr: 1.0e-3

loss_type: dice_loss
model_type: EfficientUnetb2
batch_size: 8

# scheduler_type: mslr
# scheduler_options:
#   mslr_milestone: [5,10]
#   mslr_gamma: 0.1

scheduler_type:  CosineAnnealingWarmRestarts
scheduler_options:
  t0: 1


suffix: test


dataset_resize_w: 128
dataset_resize_h: 128

epochs: 10000
manual_save_period: 100
run_valid_period: 10